#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mecha-autoship-bringup','console_scripts','mecha_autoship_lidar_node'
__requires__ = 'mecha-autoship-bringup'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mecha-autoship-bringup', 'console_scripts', 'mecha_autoship_lidar_node')()
    )
