#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'nalsem-A','console_scripts','nalsem_main_node'
__requires__ = 'nalsem-A'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('nalsem-A', 'console_scripts', 'nalsem_main_node')()
    )
