#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mecha-autoship-camera','console_scripts','mecha_autoship_filtered_image_sub_node'
__requires__ = 'mecha-autoship-camera'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mecha-autoship-camera', 'console_scripts', 'mecha_autoship_filtered_image_sub_node')()
    )
